# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e3c5d29592eb7dfc52046f6273f6df468cc46b364fa3b440a768a6abd4d891edeb1fe14fb84c7ba4ee98c9bc973a4783f928eaa62b6d9ea1fd04f062ffcedc

test:
  secret_key_base: 78c5a394675bcb67408e00ad1b3da1fc764f1993a125b643aac711d7d604557870e3517b2abadddb9366b8fb22456fc05493c83a13fb19cbb1ac3e922b3fa3d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
